# -*- coding: utf-8 -*-
"""tic_tac_toe_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c4ialsh2FLVCEl9rhQp0RwZzqMDo6GFY
"""

import os    
import time    
    
board = [' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']    
player = 1    
   
########win Flags##########    
Win = 1    
Draw = -1    
Running = 0    
Stop = 1    
###########################    
Game = Running    
Mark = 'X'    
   
#This Function Draws Game Board    
def DrawBoard1():    
    print(" %c | %c | %c " % (board[1],board[2],board[3]))    
    print("___|___|___")    
    print(" %c | %c | %c " % (board[4],board[5],board[6]))    
    print("___|___|___")    
    print(" %c | %c | %c " % (board[7],board[8],board[9]))    
    print("   |   |   ")    

def DrawBoard2():    
    print("           ____   ")
    print("          | %c  |    " % (board[1]))    
    print("      ____|____|____   ")    
    print("     | %c  | %c  | %c  |    " % (board[2],board[3],board[4]))    
    print(" ____|____|____|____|____")    
    print("| %c  | %c  | %c  | %c  | %c  |" % (board[5],board[6],board[7],board[8],board[9]))    
    print("|____|____|____|____|____|")    
   
#This Function Checks position is empty or not    
def CheckPosition(x):    
    if(board[x] == ' '):    
        return True    
    else:    
        return False    
   
#This Function Checks player has won or not    
def CheckWin1():    
    global Game    
    #Horizontal winning condition    
    if(board[1] == board[2] and board[2] == board[3] and board[1] != ' '):    
        Game = Win    
    elif(board[4] == board[5] and board[5] == board[6] and board[4] != ' '):    
        Game = Win    
    elif(board[7] == board[8] and board[8] == board[9] and board[7] != ' '):    
        Game = Win    
    #Vertical Winning Condition    
    elif(board[1] == board[4] and board[4] == board[7] and board[1] != ' '):    
        Game = Win    
    elif(board[2] == board[5] and board[5] == board[8] and board[2] != ' '):    
        Game = Win    
    elif(board[3] == board[6] and board[6] == board[9] and board[3] != ' '):    
        Game=Win    
    #Diagonal Winning Condition    
    elif(board[1] == board[5] and board[5] == board[9] and board[5] != ' '):    
        Game = Win    
    elif(board[3] == board[5] and board[5] == board[7] and board[5] != ' '):    
        Game=Win    
    #Match Tie or Draw Condition    
    elif(board[1]!=' ' and board[2]!=' ' and board[3]!=' ' and board[4]!=' ' and board[5]!=' ' and board[6]!=' ' and board[7]!=' ' and board[8]!=' ' and board[9]!=' '):    
        Game=Draw    
    else:            
        Game=Running   

def CheckWin2():    
    global Game    
    #Horizontal winning condition    
    if(board[2] == board[3] and board[3] == board[4] and board[2] != ' '):    
        Game = Win    
    elif(board[5] == board[6] and board[6] == board[7] and board[5] != ' '):    
        Game = Win    
    elif(board[6] == board[7] and board[7] == board[8] and board[6] != ' '):    
        Game = Win  
    elif(board[7] == board[8] and board[8] == board[9] and board[7] != ' '):    
        Game = Win   
    #Vertical Winning Condition    
    elif(board[1] == board[3] and board[3] == board[7] and board[1] != ' '):    
        Game = Win     
    #Diagonal Winning Condition    
    elif(board[1] == board[2] and board[2] == board[5] and board[1] != ' '):    
        Game = Win    
    elif(board[1] == board[4] and board[4] == board[9] and board[1] != ' '):    
        Game = Win       
    #Match Tie or Draw Condition    
    elif(board[1]!=' ' and board[2]!=' ' and board[3]!=' ' and board[4]!=' ' and board[5]!=' ' and board[6]!=' ' and board[7]!=' ' and board[8]!=' ' and board[9]!=' '):    
        Game=Draw    
    else:            
        Game=Running  
    
print("Tic-Tac-Toe Game Designed By Sourabh Somani")    
print("Player 1 [X] --- Player 2 [O]\n")  
choice_boardshape = input("Please select board shape (Square(3x3)-->S Pyramid-->P) : ")[0]
print()    
print()    
print("Please Wait...")    
time.sleep(3)    
if(choice_boardshape=='S'):
  while(Game == Running):    
      os.system('cls')    
      DrawBoard1()    
      if(player % 2 != 0):    
          print("Player 1's chance")    
          Mark = 'X'    
      else:    
          print("Player 2's chance")    
          Mark = 'O'    
      choice = int(input("Enter the position between [1-9] where you want to mark : "))    
      if(CheckPosition(choice)):    
          board[choice] = Mark    
          player+=1    
          CheckWin1()    
    
  os.system('cls')    
  DrawBoard1()    
  if(Game==Draw):    
      print("Game Draw")    
  elif(Game==Win):    
      player-=1    
      if(player%2!=0):    
          print("Player 1 Won")    
      else:    
          print("Player 2 Won")  
else:
  while(Game == Running):    
      os.system('cls')    
      DrawBoard2()    
      if(player % 2 != 0):    
          print("Player 1's chance")    
          Mark = 'X'    
      else:    
          print("Player 2's chance")    
          Mark = 'O'    
      choice = int(input("Enter the position between [1-9] where you want to mark : "))    
      if(CheckPosition(choice)):    
          board[choice] = Mark    
          player+=1    
          CheckWin2()    
    
  os.system('cls')    
  DrawBoard2()    
  if(Game==Draw):    
      print("Game Draw")    
  elif(Game==Win):    
      player-=1    
      if(player%2!=0):    
          print("Player 1 Won")    
      else:    
          print("Player 2 Won")